/**
 * GR Measures Data — актуальная база мер государственной поддержки инноваций (2025-2026)
 * Источники: fasie.ru, sk.ru, frp.ru, rfriti.ru, minpromtorg.gov.ru, nti.ru, corpmsp.ru, veb.ru, fpi.gov.ru, asi.ru
 */

export const GR_MEASURES = [
  // ─── Фонд содействия инновациям (fasie.ru) ───────────────────────────────────
  {
    id: 'fasie-umnik',
    source: 'fasie', source_name: 'Фонд содействия инновациям',
    name: 'УМНИК — молодёжный научно-инновационный конкурс',
    operator: 'Фонд содействия инновациям',
    type: 'grant', type_label: 'Грант',
    amount: 'до 500 тыс. ₽',
    trl_min: 1, trl_max: 4,
    sector: ['БПЛА / БАС', 'Робототехника', 'ИТ / ПО', 'Все технологические сектора'],
    criteria: ['Возраст участника до 30 лет', 'НИОКР на ранней стадии', 'Российская прописка'],
    stage: ['Pre-seed'],
    deadline: 'Ноябрь ежегодно',
    status: 'active',
    url: 'https://fasie.ru/programs/programm-umnik/',
    description: 'Поддержка молодых учёных для коммерциализации научных результатов',
  },
  {
    id: 'fasie-start1',
    source: 'fasie', source_name: 'Фонд содействия инновациям',
    name: 'СТАРТ-1 — коммерциализация инновационных разработок',
    operator: 'Фонд содействия инновациям',
    type: 'grant', type_label: 'Грант',
    amount: 'до 4 млн ₽ (фаза 1) + до 6 млн ₽ (фаза 2)',
    trl_min: 3, trl_max: 6,
    sector: ['БПЛА / БАС', 'Робототехника', 'ИТ / ПО', 'Промышленность'],
    criteria: ['ООО/АО не старше 3 лет', 'Без гос. акционеров > 25%', 'Команда до 15 человек', 'Научная новизна проекта'],
    stage: ['Pre-seed', 'Посевная'],
    deadline: 'Апрель / октябрь ежегодно',
    status: 'active',
    url: 'https://fasie.ru/programs/programm-start/',
    description: 'Поддержка малых инновационных предприятий на ранней стадии. Возможность перехода в СТАРТ-2.',
  },
  {
    id: 'fasie-start2',
    source: 'fasie', source_name: 'Фонд содействия инновациям',
    name: 'СТАРТ-2 — масштабирование инновационных проектов',
    operator: 'Фонд содействия инновациям',
    type: 'grant', type_label: 'Грант',
    amount: 'до 20 млн ₽',
    trl_min: 5, trl_max: 7,
    sector: ['БПЛА / БАС', 'Промышленность', 'Робототехника'],
    criteria: ['Завершён СТАРТ-1 или аналог', 'Первые продажи', 'Со-финансирование 50%'],
    stage: ['Посевная', 'Раунд A'],
    deadline: 'Февраль / август',
    status: 'active',
    url: 'https://fasie.ru/programs/programm-start/',
    description: 'Масштабирование проекта после прохождения СТАРТ-1 или аналогичной программы.',
  },
  {
    id: 'fasie-razvitie',
    source: 'fasie', source_name: 'Фонд содействия инновациям',
    name: 'Развитие — рост инновационных компаний',
    operator: 'Фонд содействия инновациям',
    type: 'grant', type_label: 'Грант',
    amount: 'до 30 млн ₽',
    trl_min: 6, trl_max: 9,
    sector: ['БПЛА / БАС', 'Промышленность', 'Робототехника', 'ИТ / ПО'],
    criteria: ['Выручка > 0 за последний год', 'Инновационная продукция', 'Планы по выходу на новые рынки'],
    stage: ['Раунд A', 'Раунд B'],
    deadline: 'Ежегодный конкурс',
    status: 'active',
    url: 'https://fasie.ru/programs/programm-razvitie/',
    description: 'Поддержка развития инновационных компаний с подтверждёнными продажами.',
  },

  // ─── Фонд Сколково (sk.ru) ────────────────────────────────────────────────────
  {
    id: 'sk-grant-rd',
    source: 'skolkovo', source_name: 'Фонд Сколково',
    name: 'Грант Сколково на R&D',
    operator: 'Фонд Сколково',
    type: 'grant', type_label: 'Грант',
    amount: 'до 30 млн ₽ (тип 1) / до 150 млн ₽ (тип 2)',
    trl_min: 3, trl_max: 7,
    sector: ['БПЛА / БАС', 'Робототехника', 'ИТ / ПО', 'Аэрокосмос', 'Все технологические сектора'],
    criteria: ['Статус участника Сколково', 'R&D план со сметой', 'Наличие иностранного партнёра или патента (тип 2)', 'Коммерческий потенциал'],
    stage: ['Посевная', 'Раунд A'],
    deadline: 'Rolling basis, комитет ежеквартально',
    status: 'active',
    url: 'https://sk.ru/foundation/grant/',
    description: 'Грант на проведение НИОКР до 50% бюджета R&D. Не требует возврата.',
  },
  {
    id: 'sk-status',
    source: 'skolkovo', source_name: 'Фонд Сколково',
    name: 'Статус участника Сколково (налоговые льготы)',
    operator: 'Фонд Сколково',
    type: 'tax', type_label: 'Налоговая льгота',
    amount: 'НДС 0%, страховые взносы 7.6%, налог на прибыль 0%, имущество 0%',
    trl_min: 1, trl_max: 9,
    sector: ['Все секторы'],
    criteria: ['Юрлицо в РФ', 'Выручка < 1 млрд ₽/год', 'Инновационная деятельность ≥75% выручки', 'Российские учредители ≥ 50%'],
    stage: ['Pre-seed', 'Посевная', 'Раунд A', 'Раунд B'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://sk.ru/participate/',
    description: 'Налоговые льготы на 10 лет. Основной инструмент снижения налоговой нагрузки для R&D-компаний.',
  },
  {
    id: 'sk-accelerator',
    source: 'skolkovo', source_name: 'Фонд Сколково',
    name: 'Акселератор Сколково (Startup Village)',
    operator: 'Фонд Сколково / партнёры (Сбер, ВТБ, Россети и др.)',
    type: 'accelerator', type_label: 'Акселератор',
    amount: 'Менторство + экспертиза + возможный грант до 5 млн ₽',
    trl_min: 3, trl_max: 7,
    sector: ['Все секторы'],
    criteria: ['MVP или прототип', 'Готовность к пилоту с корпорацией', 'Команда ≥ 2 человека'],
    stage: ['Pre-seed', 'Посевная'],
    deadline: 'Ежегодно (май)',
    status: 'active',
    url: 'https://startupvillage.ru/',
    description: 'Акселерация с доступом к пилотам с крупными корпорациями.',
  },

  // ─── ФРП (frp.ru) ─────────────────────────────────────────────────────────────
  {
    id: 'frp-proekty',
    source: 'frp', source_name: 'Фонд развития промышленности (ФРП)',
    name: 'Займ ФРП «Проекты развития»',
    operator: 'Фонд развития промышленности (ФРП)',
    type: 'loan', type_label: 'Займ',
    amount: 'от 5 до 500 млн ₽ по ставке 3-5% годовых',
    trl_min: 5, trl_max: 9,
    sector: ['Промышленность', 'БПЛА / БАС', 'Робототехника'],
    criteria: ['Производственный проект', 'Выручка > 0', 'Собственные средства ≥ 20%', 'Залоговое обеспечение'],
    stage: ['Раунд A', 'Раунд B'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://frp.ru/programm/proekty-razvitiya',
    description: 'Льготный займ для технологической модернизации и организации нового производства.',
  },
  {
    id: 'frp-niokr',
    source: 'frp', source_name: 'Фонд развития промышленности (ФРП)',
    name: 'Займ ФРП «НИОКР»',
    operator: 'Фонд развития промышленности (ФРП)',
    type: 'loan', type_label: 'Займ',
    amount: 'до 100 млн ₽ по ставке 0-3%',
    trl_min: 4, trl_max: 7,
    sector: ['Промышленность', 'БПЛА / БАС', 'Робототехника'],
    criteria: ['НИОКР по приоритетным технологиям', 'Патентная стратегия', 'Партнёрство с вузом или НИИ'],
    stage: ['Посевная', 'Раунд A'],
    deadline: 'Конкурсная основа',
    status: 'active',
    url: 'https://frp.ru/programm/niokr',
    description: 'Займ для финансирования НИОКР с последующей коммерциализацией.',
  },

  // ─── РФРИТ (rfriti.ru) ────────────────────────────────────────────────────────
  {
    id: 'rfriti-spp',
    source: 'rfriti', source_name: 'РФРИТ / Минцифры',
    name: 'Грант РФРИТ на разработку СППО',
    operator: 'РФРИТ (Российский фонд развития информационных технологий)',
    type: 'grant', type_label: 'Грант',
    amount: 'до 500 млн ₽ (50% бюджета проекта)',
    trl_min: 4, trl_max: 8,
    sector: ['ИТ / ПО', 'Промышленность'],
    criteria: ['Разработка СППО', 'ОКВЭД 62/63', 'Приоритетное ПО', 'Первые клиенты или LOI', 'Российское юрлицо'],
    stage: ['Посевная', 'Раунд A', 'Раунд B'],
    deadline: 'Конкурсная основа, 1-2 волны в год',
    status: 'active',
    url: 'https://rfriti.ru/measures/',
    description: 'Крупнейший грант для разработчиков ПО. Не возвращается при выполнении KPI.',
  },
  {
    id: 'rfriti-ai',
    source: 'rfriti', source_name: 'РФРИТ / Минцифры',
    name: 'Грант РФРИТ «Промышленный ИИ»',
    operator: 'РФРИТ',
    type: 'grant', type_label: 'Грант',
    amount: 'до 300 млн ₽',
    trl_min: 5, trl_max: 8,
    sector: ['ИТ / ПО', 'Промышленность', 'БПЛА / БАС'],
    criteria: ['AI/ML решения для промышленности', 'Пилот с предприятием', 'ГОСТ Р 59990'],
    stage: ['Посевная', 'Раунд A'],
    deadline: 'Ежегодно',
    status: 'active',
    url: 'https://rfriti.ru/measures/',
    description: 'Поддержка внедрения AI в производственные процессы.',
  },

  // ─── Минпромторг ──────────────────────────────────────────────────────────────
  {
    id: 'minprom-719',
    source: 'minprom', source_name: 'Минпромторг РФ',
    name: 'Постановление 719 — российское происхождение',
    operator: 'Минпромторг РФ',
    type: 'status', type_label: 'Статус',
    amount: 'Доступ к ограниченным госзакупкам, субсидии на производство',
    trl_min: 7, trl_max: 9,
    sector: ['БПЛА / БАС', 'Промышленность', 'Аэрокосмос'],
    criteria: ['Локализация ≥ 70% (для БПЛА ≥ 80%)', 'Документальное подтверждение', 'Аудит Минпромторга'],
    stage: ['Раунд A', 'Раунд B'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://minpromtorg.gov.ru/',
    description: 'Критический статус для участия в госзакупках по 44-ФЗ и 223-ФЗ.',
  },
  {
    id: 'minprom-niokr',
    source: 'minprom', source_name: 'Минпромторг РФ',
    name: 'Субсидия на НИОКР (ПП РФ №1649)',
    operator: 'Минпромторг РФ',
    type: 'subsidy', type_label: 'Субсидия',
    amount: 'до 300 млн ₽ (50-70% затрат)',
    trl_min: 3, trl_max: 7,
    sector: ['Промышленность', 'БПЛА / БАС', 'Аэрокосмос', 'Робототехника'],
    criteria: ['НИОКР по приоритетным технологиям', 'Соисполнитель — ОПК или вуз', 'Нет иностранных акционеров > 49%'],
    stage: ['Посевная', 'Раунд A'],
    deadline: 'Конкурс 1 раз в год',
    status: 'active',
    url: 'https://minpromtorg.gov.ru/activities/support/',
    description: 'Крупнейший инструмент Минпромторга для финансирования ОКР.',
  },
  {
    id: 'minprom-bas',
    source: 'minprom', source_name: 'Минпромторг / Нацпроект БАС',
    name: 'Субсидии Нацпроекта БАС 2024–2030',
    operator: 'Минпромторг / Минтранс / Минэко',
    type: 'subsidy', type_label: 'Субсидия',
    amount: 'до 300 млн ₽ на компанию',
    trl_min: 6, trl_max: 9,
    sector: ['БПЛА / БАС'],
    criteria: ['Включение в реестр производителей БАС', 'Контракт с заказчиком 2025+', 'TRL ≥ 6', 'Собственное производство в РФ'],
    stage: ['Раунд A', 'Раунд B'],
    deadline: 'Плановый период 2025-2030',
    status: 'active',
    url: 'https://bas.gov.ru/',
    description: 'Ключевой инструмент Нацпроекта БАС. Охватывает производителей аппаратов и систем управления.',
  },

  // ─── НТИ ──────────────────────────────────────────────────────────────────────
  {
    id: 'nti-aeronet',
    source: 'nti', source_name: 'НТИ «Аэронет»',
    name: 'Грант НТИ «Аэронет» (дорожная карта)',
    operator: 'НТИ / АНО «Платформа НТИ» / Минэкономразвития',
    type: 'grant', type_label: 'Грант',
    amount: 'до 100 млн ₽',
    trl_min: 4, trl_max: 8,
    sector: ['БПЛА / БАС', 'Аэрокосмос'],
    criteria: ['Проект в периметре дорожной карты Аэронет', 'Партнёрство с якорным заказчиком', 'Технологическая уникальность'],
    stage: ['Посевная', 'Раунд A'],
    deadline: 'Ежегодный конкурс (осень)',
    status: 'active',
    url: 'https://nti.ru/activities/roadmaps/aeronet/',
    description: 'Приоритетный инструмент для проектов в сфере беспилотных авиационных систем.',
  },
  {
    id: 'nti-technet',
    source: 'nti', source_name: 'НТИ «Технет» / «Нейронет»',
    name: 'Грант НТИ «Технет» / «Нейронет»',
    operator: 'НТИ / Иннопрактика',
    type: 'grant', type_label: 'Грант',
    amount: 'до 50 млн ₽',
    trl_min: 3, trl_max: 7,
    sector: ['Робототехника', 'Промышленность', 'ИТ / ПО'],
    criteria: ['Проект в периметре дорожных карт НТИ', 'Работа с образовательными организациями', 'Технологическая новизна'],
    stage: ['Pre-seed', 'Посевная'],
    deadline: 'Конкурсная основа',
    status: 'active',
    url: 'https://nti.ru/activities/roadmaps/',
    description: 'Поддержка технологических проектов в рамках дорожных карт НТИ.',
  },

  // ─── МСП / ВЭБ.РФ ────────────────────────────────────────────────────────────
  {
    id: 'corpmsp-kredit',
    source: 'corpmsp', source_name: 'Корпорация МСП / МСП Банк',
    name: 'Льготное кредитование МСП (программа ПСК)',
    operator: 'МСП Банк / уполномоченные банки',
    type: 'loan', type_label: 'Займ',
    amount: 'до 2 млрд ₽ по ставке КС-3%',
    trl_min: 1, trl_max: 9,
    sector: ['Все секторы'],
    criteria: ['Статус МСП (ФНС)', 'Выручка < 2 млрд ₽/год', 'Без задолженности по налогам'],
    stage: ['Pre-seed', 'Посевная', 'Раунд A', 'Раунд B'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://corpmsp.ru/patsientam/msp/kredit/',
    description: 'Базовый инструмент льготного кредитования для любого МСП. Доступен через 60+ банков-партнёров.',
  },
  {
    id: 'corpmsp-garantiya',
    source: 'corpmsp', source_name: 'Корпорация МСП',
    name: 'Гарантия МСП Банка (замена залога)',
    operator: 'МСП Банк / региональные гарантийные организации',
    type: 'guarantee', type_label: 'Гарантия',
    amount: 'Гарантия до 70% суммы кредита (до 500 млн ₽)',
    trl_min: 1, trl_max: 9,
    sector: ['Все секторы'],
    criteria: ['Статус МСП', 'Проект в приоритетных отраслях', 'Нехватка залогового обеспечения'],
    stage: ['Pre-seed', 'Посевная', 'Раунд A'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://corpmsp.ru/patsientam/msp/garantiya/',
    description: 'Позволяет получить кредит без полного залога. Критически важен для стартапов без активов.',
  },
  {
    id: 'veb-tech',
    source: 'veb', source_name: 'ВЭБ.РФ',
    name: 'Проектное финансирование ВЭБ.РФ',
    operator: 'ВЭБ.РФ',
    type: 'loan', type_label: 'Займ',
    amount: 'от 500 млн ₽, ставка ниже рынка',
    trl_min: 7, trl_max: 9,
    sector: ['Промышленность', 'БПЛА / БАС'],
    criteria: ['Крупный промышленный проект', 'Эффект для национальных целей', 'Залоговое обеспечение или госгарантия'],
    stage: ['Раунд B', 'Growth'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://veb.ru/projects/',
    description: 'Проектное финансирование крупных инициатив для масштабирования после Раунда B.',
  },

  // ─── Специализированные ───────────────────────────────────────────────────────
  {
    id: 'napo-cert',
    source: 'napo', source_name: 'Росавиация / НАПО',
    name: 'Сертификация БПЛА (АП-21 / АП-22)',
    operator: 'Росавиация / НАПО',
    type: 'status', type_label: 'Статус',
    amount: 'Компенсация до 50% затрат на сертификацию',
    trl_min: 7, trl_max: 9,
    sector: ['БПЛА / БАС'],
    criteria: ['Разработчик воздушного судна', 'БПЛА взлётной массой ≥ 30 кг', 'Заявка в Росавиацию'],
    stage: ['Раунд A', 'Раунд B'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://favt.ru/',
    description: 'Обязательный статус для коммерческой эксплуатации БПЛА.',
  },
  {
    id: 'fpi-techdir',
    source: 'fpi', source_name: 'ФПИ — Фонд перспективных исследований',
    name: 'Программа технологического прорыва (ФПИ)',
    operator: 'Фонд перспективных исследований',
    type: 'grant', type_label: 'Грант',
    amount: 'Индивидуально (от 50 млн ₽)',
    trl_min: 6, trl_max: 9,
    sector: ['БПЛА / БАС', 'Робототехника', 'ИТ / ПО'],
    criteria: ['Технология двойного назначения', 'Уникальность разработки', 'Готовность к испытаниям'],
    stage: ['Раунд A', 'Раунд B'],
    deadline: 'По приглашению',
    status: 'active',
    url: 'https://fpi.gov.ru/',
    description: 'Финансирование прорывных технологий оборонного и двойного назначения.',
  },
  {
    id: 'asi-natproject',
    source: 'asi', source_name: 'АСИ — Агентство стратегических инициатив',
    name: 'Включение в Национальный проект (через АСИ)',
    operator: 'АСИ / профильные министерства',
    type: 'status', type_label: 'Статус',
    amount: 'Доступ к финансированию нацпроектов',
    trl_min: 5, trl_max: 9,
    sector: ['Все секторы'],
    criteria: ['Проект имеет общенациональное значение', 'Рекомендация рабочей группы АСИ', 'Масштабируемость на всю страну'],
    stage: ['Раунд A', 'Раунд B'],
    deadline: 'Через заявку на Форуме АСИ',
    status: 'active',
    url: 'https://asi.ru/',
    description: 'Включение в орбиту нацпроектов открывает доступ к субсидиям и госзаказу.',
  },
  {
    id: 'minprom-spik',
    source: 'minprom', source_name: 'Минпромторг РФ',
    name: 'Специальный инвестиционный контракт (СПИК 2.0)',
    operator: 'Минпромторг РФ / регион',
    type: 'status', type_label: 'Статус',
    amount: 'Налоговые льготы + госзаказ + снижение арендных ставок',
    trl_min: 6, trl_max: 9,
    sector: ['Промышленность', 'БПЛА / БАС'],
    criteria: ['Инвестиции ≥ 750 млн ₽', 'Производство в РФ', 'Новейшая технология', 'Срок 5-20 лет'],
    stage: ['Раунд B', 'Growth'],
    deadline: 'Rolling basis',
    status: 'active',
    url: 'https://minpromtorg.gov.ru/activities/spik/',
    description: 'Механизм долгосрочной защиты инвесторов с гарантией неизменности условий.',
  },
]

/**
 * Подобрать меры под профиль стартапа
 */
export function matchMeasuresForProject(project) {
  const { trl = 4, subFundName = 'БАС', stageName = 'Посевная' } = project

  const sectorMap = {
    'БАС': ['БПЛА / БАС', 'Аэрокосмос', 'Все секторы'],
    'РОБО': ['Робототехника', 'Промышленность', 'ИТ / ПО', 'Все секторы'],
    'МЭ': ['Промышленность', 'ИТ / ПО', 'Все секторы'],
  }
  const relevantSectors = sectorMap[subFundName] || sectorMap['БАС']

  return GR_MEASURES.filter(m => {
    const trlOk = trl >= (m.trl_min || 1) && trl <= (m.trl_max || 9)
    const sectorOk = !m.sector?.length || m.sector.some(s => relevantSectors.includes(s))
    return trlOk && sectorOk && m.status !== 'closed'
  })
}
